#!/usr/bin/bash
whoami=yunqi

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
mako &

# waybar
$scripts/launch_waybar &

# wallpaper
$scripts/wall $config/wallpapers/4.jpg &

# effects
#$scripts/rgb &

# other
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "hello $(whoami)" &

python ~/test.py &
