[default_view]

keymap = [
	{ keys = [ "t", "u" ],		command = "new_tab --current" },
	{ keys = [ "q" ],		command = "close_tab" },
	{ keys = [ "ctrl+c" ],		command = "quit" },
	{ keys = [ "Q" ],		command = "quit --output-current-directory" },

	{ keys = [ "R" ],		command = "reload_dirlist" },
	{ keys = [ "z", "h" ],		command = "toggle_hidden" },
	{ keys = [ "ctrl+h" ],		command = "toggle_hidden" },
	{ keys = [ "t", "i" ],		command = "tab_switch 1" },
	{ keys = [ "t", "n" ],		command = "tab_switch -1" },

	{ keys = [ "alt+1" ],		command = "tab_switch_index 1" },
	{ keys = [ "alt+2" ],		command = "tab_switch_index 2" },
	{ keys = [ "alt+3" ],		command = "tab_switch_index 3" },
	{ keys = [ "alt+4" ],		command = "tab_switch_index 4" },
	{ keys = [ "alt+5" ],		command = "tab_switch_index 5" },

	# arrow keys
	# { keys = [ "arrow_up" ],	command = "cursor_move_up" },
	# { keys = [ "arrow_down" ],	command = "cursor_move_down" },
	# { keys = [ "arrow_left" ],	command = "cd .." },
	# { keys = [ "arrow_right" ],	command = "open" },
	{ keys = [ "\n" ],		command = "open" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },
	{ keys = [ "page_up" ],		command = "cursor_move_page_up" },
	{ keys = [ "page_down" ],	command = "cursor_move_page_down" },
	{ keys = [ "ctrl+u" ],  	command = "cursor_move_page_up 0.5" },
	{ keys = [ "ctrl+e" ], 		command = "cursor_move_page_down 0.5" },

	# vim-like keybindings
	{ keys = [ "e" ],		command = "cursor_move_down" },
	{ keys = [ "u" ],		command = "cursor_move_up" },
	{ keys = [ "E" ],		command = "cursor_move_down 5" },
	{ keys = [ "U" ],		command = "cursor_move_up 5" },
	{ keys = [ "n" ],		command = "cd .." },
	{ keys = [ "h" ],		command = "cd -" },
	{ keys = [ "i" ],		command = "open" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },
	{ keys = [ "r" ],		command = "open_with" },

	# { keys = [ "H" ],		command = "cursor_move_page_home" },
	# { keys = [ "L" ],		command = "cursor_move_page_middle" },
	# { keys = [ "M" ],		command = "cursor_move_page_end" },

	{ keys = [ "[" ],		command = "parent_cursor_move_up" },
	{ keys = [ "]" ],		command = "parent_cursor_move_down" },

	{ keys = [ "c", "d" ],		command = ":cd " },
	{ keys = [ "d", "d" ],		command = "cut_files" },
	{ keys = [ "y", "y" ],		command = "copy_files" },
	{ keys = [ "y", "n" ],		command = "copy_filename" },
	{ keys = [ "y", "." ],		command = "copy_filename_without_extension" },
	{ keys = [ "y", "p" ],		command = "copy_filepath" },
	{ keys = [ "y", "d" ],		command = "copy_dirpath" },

	{ keys = [ "delete" ],		command = "delete_files" },
	{ keys = [ "d", "D" ],		command = "delete_files" },

	{ keys = [ "p", "p" ],		command = "paste_files" },
	{ keys = [ "p", "o" ],		command = "paste_files --overwrite=true" },

	{ keys = [ "a" ],		command = "rename_append" },
	{ keys = [ "k" ],		command = "rename_prepend" },

	{ keys = [ "T" ],		command = ":touch " },

	{ keys = [ " " ],		command = "select --toggle=true" },
	{ keys = [ "v" ],		command = "select --all=true --toggle=true" },
	{ keys = [ "w" ],		command = "show_tasks --exit-key=w" },
	{ keys = [ "c", "b" ],		command = "bulk_rename" },
	{ keys = [ "c", "m" ],		command = "set_mode" },
	{ keys = [ "c", "n" ],		command = ":rename " },

	{ keys = [ ":" ],		command = ":" },
	{ keys = [ ";" ],		command = ":" },

	{ keys = [ "'" ],		command = ":shell " },
	{ keys = [ "S" ],		command = "shell zsh" },
	{ keys = [ "ctrl+g" ],		command = "shell lazygit" },
	{ keys = [ "M" ],		command = ":mkdir " },

	{ keys = [ "/" ],		command = ":search_inc " },
	{ keys = [ "f" ],		command = ":filter  " },
	# { keys = [ "/" ],		command = ":search " },
	# { keys = [ "|" ],		command = ":search_inc " },
	{ keys = [ "\\" ],		command = ":search_glob " },
	# { keys = [ "ctrl+f" ],		command = "search_fzf" },
	{ keys = [ "ctrl+f" ],		command = "subdir_fzf" },
	{ keys = [ "ctrl+p" ],		command = "subdir_fzf" },

	{ keys = [ "=" ],		command = "search_next" },
	{ keys = [ "-" ],		command = "search_prev" },

	{ keys = [ "o", "r" ],		command = "sort reverse" },
	{ keys = [ "o", "l" ],		command = "sort lexical" },
	{ keys = [ "o", "m" ],		command = "sort mtime" },
	{ keys = [ "o", "c" ],		command = "sort mtime" },
	{ keys = [ "o", "n" ],		command = "sort natural" },
	{ keys = [ "o", "s" ],		command = "sort size" },
	{ keys = [ "o", "e" ],		command = "sort ext" },

	{ keys = [ "g", "r" ],		command = "cd /" },
	{ keys = [ "g", "d" ],		command = "cd ~/Downloads" },
	{ keys = [ "g", "D" ],		command = "cd ~/Desktop" },
	{ keys = [ "g", "e" ],		command = "cd /etc" },
	{ keys = [ "g", "h" ],		command = "cd ~/" },
	{ keys = [ "g", "p" ],		command = "cd ~/prog" },
	{ keys = [ "g", "i" ],		command = "cd ~/Github" },
	{ keys = [ "g", "f", "f" ],		command = "cd ~/.config" },
	{ keys = [ "g", "f", "n" ],		command = "cd ~/.config/nvim" },
	{ keys = [ "g", "f", "z" ],		command = "cd ~/.config/zsh" },
	{ keys = [ "g", "f", "j" ],		command = "cd ~/.config/joshuto" },
	{ keys = [ "g", "f", "l" ],		command = "cd ~/.config/jesseduffield/lazygit" },
	{ keys = [ "?" ],		command = "help" }
]

[task_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "e" ],		command = "cursor_move_down" },
	{ keys = [ "u" ],		command = "cursor_move_up" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
]

[help_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "e" ],		command = "cursor_move_down" },
	{ keys = [ "u" ],		command = "cursor_move_up" },
	{ keys = [ "E" ],		command = "cursor_move_down 5" },
	{ keys = [ "U" ],		command = "cursor_move_up 5" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
	{ keys = [ "q" ],		command = "show_tasks" },
]
